# Site settings
title: Fianbakken [dot] com
description: A developers rants, fairytales and other comments on life.
keywords: Developer, Azure, Cloud, dotnet
author: Harald S. Fianbakken
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://text.fianbakken.com/" # the base hostname & protocol for your site
owner:
    name: Harald Fianbakken
    email: harald.fianbakken "at" gm[ail][dot]com
    github: haraldfianbakken
    twitter: Cmdrtchort
    linkedin: haraldfianbakken
    facebook:
    google_plus:
    youtube:

# Post sharing icons
sharing:
    twitter: true
    linkedin: true
    facebook: true
    google_plus: true
    reddit: true

# Disqus comments configuration (leave blank to disable comments)
disqus_shortname: 'textfianbakken'

# Jekyll configuration
permalink: /:year/:month/:day/:title/
paginate: 8
gems: ['jekyll-paginate']

# Exclude
exclude: ['README.md']